/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native void Callback_set(long jarg1);
  public final static native long Callback_get();
  public final static native void Caller_set(long jarg1);
  public final static native long Caller_get();
}
