/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaspertest;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.swing.JRViewerController;
import net.sf.jasperreports.swing.JRViewerPanel;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mani
 */
public class JasperFrame extends javax.swing.JFrame implements ActionListener {

    private final DefaultTableModel tbmRpt;

    private Timer timer;

    /**
     * Creates new form JasperFrame
     */
    public JasperFrame() {

        initComponents();

        String[] columnNames = {"Id", "Name", "Department", "Email"};
        
        String[][] data = {
            {"111", "G Conger", " Orthopaedic", "jim@wheremail.com"},
            {"222", "A Date", "ENT", "adate@somemail.com"},
            {"333", "R Linz", "Paedriatics", "rlinz@heremail.com"},
            {"444", "V Sethi", "Nephrology", "vsethi@whomail.com"},
            {"555", "K Rao", "Orthopaedics", "krao@whatmail.com"},
            {"666", "V Santana", "Nephrology", "vsan@whenmail.com"},
            {"777", "J Pollock", "Nephrology", "jpol@domail.com"},
            {"888", "H David", "Nephrology", "hdavid@donemail.com"},
            {"999", "P Patel", "Nephrology", "ppatel@gomail.com"},
            {"101", "C Comer", "Nephrology", "ccomer@whymail.com"}
        };
        
        tbmRpt = new DefaultTableModel();

        //tabJasper.setModel(tbmRpt);
        tbmRpt.addColumn("Id");
        tbmRpt.addColumn("Name");
        tbmRpt.addColumn("Department");
        tbmRpt.addColumn("Email");
//
//         
//        
        Object[] row = {"111", "Mani", "Address1", "mani@gmail.com"};
//
        tbmRpt.addRow(row);
        tbmRpt.addRow(row);
        tbmRpt.addRow(row);
        tbmRpt.addRow(row);
        tbmRpt.addRow(row);
        tbmRpt.addRow(row);
        printSimpleReport();
//
        timer = new Timer(500, this);
        timer.start();
        hashMap = new HashMap();
        
        //hashMap.put("isTitleNewPage", "true");
        hashMap.put("isIgnorePagination", "true");
    }

    HashMap hashMap;
    boolean add = false;
    JasperPrint jasperPrint = null;
    CustJRViewer viewer;

    public void printSimpleReport() {

        try {
            if(!add){
            JasperCompileManager.compileReportToFile("/home/mani/java_proj/JasperTest/lib/styleRep.jrxml");
            }

            JRTableModelDataSource jrTableModelDataSource = new JRTableModelDataSource(tbmRpt);

            
            
            jasperPrint = JasperFillManager.fillReport("/home/mani/java_proj/JasperTest/lib/styleRep.jasper", hashMap,
                    jrTableModelDataSource);

            
            //JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            //JRViewerController control=new JRViewerController(null, null).refreshPage();
            //JRViewerPanel panel=new JRViewerPanel()
            if (!add) {
                viewer = new CustJRViewer(jasperPrint);
                
                this.add(viewer, BorderLayout.CENTER);

                add = true;
            } else {
                viewer.loadReport(jasperPrint);                
                
                
            }

            //viewer.setZoomRatio(2);
            //}
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {

                    JasperFrame.this.validate();
                    JasperFrame.this.repaint();

                }
            });

            //jasperViewer.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panControl = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        butAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setColumns(10);
        panControl.add(jTextField1);

        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });
        panControl.add(butAdd);

        getContentPane().add(panControl, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int idx = 222;
    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Object[] row = {Integer.toString(idx++), "Mani", "Address1", "mani@gmail.com"};

        tbmRpt.addRow(row);

        printSimpleReport();
    }//GEN-LAST:event_butAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JasperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JasperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JasperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JasperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JasperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panControl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        butAdd.doClick();
    }
}
