/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native int gcd(int jarg1, int jarg2);
  public final static native void Foo_set(double jarg1);
  public final static native double Foo_get();
  public final static native void printVal();
  public final static native void vec_set(long jarg1, Vector jarg1_);
  public final static native long vec_get();
  public final static native void Vector_x_set(long jarg1, Vector jarg1_, int jarg2);
  public final static native int Vector_x_get(long jarg1, Vector jarg1_);
  public final static native void Vector_y_set(long jarg1, Vector jarg1_, int jarg2);
  public final static native int Vector_y_get(long jarg1, Vector jarg1_);
  public final static native void Vector_z_set(long jarg1, Vector jarg1_, int jarg2);
  public final static native int Vector_z_get(long jarg1, Vector jarg1_);
  public final static native long new_Vector();
  public final static native void delete_Vector(long jarg1);
}
