/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static int gcd(int x, int y) {
    return exampleJNI.gcd(x, y);
  }

  public static void setFoo(double value) {
    exampleJNI.Foo_set(value);
  }

  public static double getFoo() {
    return exampleJNI.Foo_get();
  }

  public static void printVal() {
    exampleJNI.printVal();
  }

  public static void setVec(Vector value) {
    exampleJNI.vec_set(Vector.getCPtr(value), value);
  }

  public static Vector getVec() {
    long cPtr = exampleJNI.vec_get();
    return (cPtr == 0) ? null : new Vector(cPtr, false);
  }

}
